### PR TITLE
Merge branch 'master' of github.com:zauberlabs/gnip4j

### PR DESCRIPTION
**Pull request by jmmk**

### CODE REVIEW

**Comment by bbguitar77** [comment]
Do we still need to maintain our own version? I see we added some mock capabilities and a few other things but have no idea whether those things are supported out-of-the-box now or if we still need them

**Comment by jmmk** [comment]
@bbguitar77 the primary difference is the Replay functionality

**Comment by bbguitar77** [comment]
LGTM as far as I can tell

**Comment by KidA78** [comment]
@bbguitar77 @jmmk Any reason we can't open this PR against the main repo and get it accepted into the main codebase?  Those extra things I wrote back in the day really helped from an implementation and testing perspective. Are we actively using Replay and the mock stuff?  If so we should make a case for us being contributors

**Comment by jmmk** [comment]
@KidA78 https://github.com/zauberlabs/gnip4j/issues/51 I asked when we did the gnip 2.0 update and got no response

We don't have to touch gnip4j often so I don't think it's worth the effort

**Pull request merged**
